title: stale
description: A CLI tool to run or skip commands based on file content hashes
url: https://th1nkful.github.io
baseurl: /stale

remote_theme: just-the-docs/just-the-docs@v0.10.1

color_scheme: light

permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock

aux_links:
  "View on GitHub":
    - "https://github.com/th1nkful/stale"

footer_content: "Licensed under the Apache License 2.0."
